name: openresource
services:
  frontend:
    build:
      context: frontend
      target: development
    networks:
      - client-side
    ports:
      - 3000:3000
    volumes:
      - ./src:/code/src:ro
    environment:
      - BACKEND_URL=localhost:8000
    depends_on:
      backend:
        condition: service_healthy
  backend:
    build:
      context: backend
      target: development
    networks:
      - client-side
      - server-side
    ports:
      - 8000:8000
    environment:
      - PORT=8000
      - DATABASE_URL=postgres://postgres:notagoodpassword@host.docker.internal:5432/openresource
      - HOST=0.0.0.0
      - RUST_LOG=info
    depends_on:
      database:
        condition: service_healthy
  database:
    image: postgres:bookworm
    restart: always
    environment:
      - POSTGRES_PASSWORD="notagoodpassword"
    networks:
      - server-side
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
networks:
  client-side: {}
  server-side: {}
volumes:
  backend-cache: {}
  db-data: {}
