name: openresource
services:
#  frontend:
#    build:
#      context: frontend
#      target: builder
#    networks:
#      - frontend
#    ports:
#      - 3000:3000
#    volumes:
#      - ./frontend/src:/code/src:ro
#    environment:
#      - BACKEND_URL:localhost:8000
#      - HOSTNAME="0.0.0.0"
#    command: node /code/src/server.js
#    depends_on:
#      backend:
#        condition: service_healthy

  backend:
    build: backend
    command: cargo run
    volumes:
      - backend-cache:/root/.cargo
    environment:
      - PORT=8000
      - DATABASE_URL=postgres://openresource:openresource@database:5432/openresource
      - HOST=0.0.0.0
      - RUST_LOG=info
    depends_on:
      - database
    ports:
      - 8000:8000

  database:
    image: postgres:bookworm
    environment:
      - POSTGRES_DB=openresource
      - POSTGRES_USER=openresource
      - POSTGRES_PASSWORD=openresource
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  backend-cache: {}
  db-data: {}
