name: openresource
services:
  frontend:
    build:
      context: frontend
      target: development
    networks:
      - client-side
    ports:
      - 3000:3000
    volumes:
      - ./backend:/code/src:ro
    env_file:
      - ./frontend/.env
    depends_on:
      backend:
        condition: service_healthy
  backend:
    build:
      context: backend
      target: development
    networks:
      - client-side
      - server-side
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env
    depends_on:
      database:
        condition: service_healthy
  database:
    image: postgres:bookworm
    restart: always
    env_file:
      - ./backend/.env
    networks:
      - server-side
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
networks:
  client-side: {}
  server-side: {}
volumes:
  backend-cache: {}
  db-data: {}
