name: openresource
services:
  frontend:
    build:
      context: frontend
      target: builder
    networks:
      - frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/code/src:ro
    environment:
      - BACKEND_URL:localhost:8000
      - HOSTNAME="0.0.0.0"
    command: node /code/src/server.js
    depends_on:
      backend:
        condition: service_healthy

  backend:
    build:
      context: backend
      target: builder
    networks:
      - frontend
      - backend
    ports:
      - 8000:8000
    environment:
      - PORT=8000
      - DATABASE_URL=postgres://postgres:postgres@host.docker.internal:5432/openresource
      - HOST=0.0.0.0
      - RUST_LOG=info
    command: /srv/openresource
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:bookworm
    restart: always
    environment:
      - POSTGRES_DB=openresource
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - backend
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 10s
      retries: 10

networks:
  frontend: {}
  backend: {}

volumes:
  backend-cache: {}
  database: {}
