#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER $DEV_USER;
	CREATE DATABASE $DEV_DB;
	GRANT ALL PRIVILEGES ON DATABASE $DEV_DB TO $DEV_USER;
EOSQL
